# Generated by Django 5.0.6 on 2024-06-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgoraApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speechhistory',
            name='input_contents',
        ),
        migrations.RemoveField(
            model_name='speechhistory',
            name='reply_contents',
        ),
        migrations.AddField(
            model_name='speechhistory',
            name='content',
            field=models.JSONField(default=list),
        ),
    ]
